Task_1_1_2
lnkpv/OOP pull request #2
Opened 2023-09-22 05:07 UTC by lnkpv

2023-09-22 08:52 UTC, galinabykova requested changes

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/yakupova/HeapSort.class
вот это не надо добавлять в гитхаб

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/yakupova/HeapSort.class
вообще странно, что у тебя тут добавляется первая лаба полностью. Кажется, что ты что-то сделала странненько, возможно у тебя будут сложности с мёржем дальше. Но я верю, ты их преодолеешь

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_1/.idea/gradle.xml
не добавляй папку .idea, добавь её в .gitignore полностью. Если считаешь, что это полезные файлы, надо меня в этом убедить

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/yakupova/Polynomial.java
> +        this.coefficients = coefficients;
здесь передача по ссылке или по значению? так и задумывалось?

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/yakupova/Polynomial.java
> +    public String to_string() {
нужно переопределять стандартный toString

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/yakupova/Polynomial.java
> +    public boolean equals(Polynomial other) {
вместе с equals нужно переопределять hashCode
https://javarush.com/groups/posts/3957-kofe-breyk-168-zachem-pereopredeljatjh-metodih-equals-i-hashcode-v-java

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/yakupova/PolynomialTest.java
> +        assertTrue(p3.equals(p1.plus(p2)));
должен быть assert, который проверяет на равенство объекты, лучше использовать его, потому что так вывод при падении теста будет приятнее. Не просто будет написано true или false, а будут писать прям объекты, которые оказались не равными

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/yakupova/PolynomialTest.java
> +    void checkPlus() {
лучше добавить в название, что это тест на сложении именно ПОЛИНОМОВ, название теста должно быть понятно, даже если ты не знаешь, про что проект

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/yakupova/PolynomialTest.java
> +    void checkMain() {
в этой задаче ты должна пройти порог по покрытию без этого теста, удали его, пожалуйста

2023-09-22 08:52 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/yakupova/PolynomialTest.java
хочется больше одного содержательного теста на операцию

2023-09-25 11:54 UTC, lnkpv commented on Task_1_1_2/src/main/java/ru/nsu/yakupova/Polynomial.java
> +        this.coefficients = coefficients;
Пока это писала, слабо понимала как работает передача данных в джаве. Почитала про это отдельно и вроде более менее разобралась. Добавила .clone(), чтобы клонировать себе значения и не было бед со ссылками.

2023-09-25 17:05 UTC, galinabykova requested changes

2023-09-25 17:05 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/yakupova/Polynomial.java
> +    public boolean equals(Object other) {
подумай, что произойдёт если other будет не Polynomial

2023-09-25 17:28 UTC, lnkpv commented on Task_1_1_2/src/main/java/ru/nsu/yakupova/Polynomial.java
> +    public boolean equals(Object other) {
Решила сделать три исхода:
1) Если other - Polynomial - все ок
2) Если other - int[] - Делаем его Polynomial
3) otherwise - false

2023-09-25 18:08 UTC, galinabykova approved these changes

2023-09-26 00:28 UTC, merged