create Task_1_2_1
lnkpv/OOP pull request #3
Opened 2023-10-04 15:34 UTC by lnkpv

2023-10-07 15:11 UTC, lnkpv commented
Я сделала основное задание. Всё кроме BFS (на момент 07.10). Хочу узнать, нужно ли что-то сильно менять, пока BFS не написала.

2023-10-08 18:36 UTC, galinabykova commented
> Я сделала основное задание. Всё кроме BFS (на момент 07.10). Хочу узнать, нужно ли что-то сильно менять, пока BFS не написала.

общая идея верная

2023-10-09 08:54 UTC, galinabykova requested changes

2023-10-09 08:54 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/yakupova/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
я бы, наверно, итерировалась по элементам (Iterable T), оставляя все детали реализации в итераторе. Ты обдумывала такой вариант и, если да, почему от него отказалась?

2023-10-09 08:54 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/yakupova/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
так, например, делает лист (List T - это Iterable T)

2023-10-09 08:54 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/yakupova/Tree.java
> +    public void remove() {
что произойдёт в твоей реализации, если удалить элемент в процессе итерирования?

2023-10-17 03:35 UTC, lnkpv commented
Итак, я поняла, что имелось ввиду насчет Iterable T. Поэтому переписала. BFS и DFS вместе с реализацией итераторов разбила на два класса.
Насчет remove() : если remove срабатывает в итераторе, то удаляется элемент дерева (+ его дети). Причем удаляется как из дерева, так и из очереди (с помощью очереди реализованы BFS, DFS).

2023-10-17 03:36 UTC, lnkpv commented
Я пока не поняла, почему основной файл с Tree так портит проценты, надеюсь, что выясню

2023-10-17 04:05 UTC, galinabykova requested changes
reviewdog

2023-10-17 04:05 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/yakupova/Tree.java
> +    public void remove() {
тебе нужно бросать исключение в случае, когда продолжение итерирования невозможно из-за изменения коллекции извне, например, методом remove дерева (ConcurrentModificationException)

2023-10-17 09:17 UTC, lnkpv commented
Я поставила флаг блокировки: Когда итератор получает дерево(поддерево), все его элементы помечаются заблокированными. А все функции изменения  (добавление, удаление) начинаются с проверки на то, является ли вершина или какой-то из ее предков заблокированным. Добавила тесты на проверку корректности remove

2023-10-17 09:39 UTC, galinabykova approved these changes
Привет, я не буду просить тебя исправить, потому что всем остальным я засчитывала это решение, но пару часов назад я осознала, что способ с блокировкой не совсем корректен. Сейчас напишу об этом сообщение в чат

2023-10-17 15:12 UTC, merged