Task_1_2_2
lnkpv/OOP pull request #4
Opened 2023-10-25 14:50 UTC by lnkpv

2023-10-25 16:10 UTC, lnkpv commented
Я пишу кучу тестов, но проценты вообще не хотят подниматься. Я не знаю, что с этим делать((

2023-10-25 17:02 UTC, galinabykova commented
> Я пишу кучу тестов, но проценты вообще не хотят подниматься. Я не знаю, что с этим делать((

В IDEA можно запустить тесты с покрытием (тыкаешь на проект -> More Run/Debug -> Run... with coverage). После того, как тесты отработают, будет видно, какие строчки покрыты тестами, какие нет. Это может помочь. На мягкий дедлайн нужно хотя бы общее покрытие тестами больше порога

2023-10-25 17:31 UTC, lnkpv commented
Спасибо!!! это помогло. Все рушил toString. На него не было явных тестов (сразу принт), а строчек он занимает много. Добавила на него тесты и процент взлетел @galinabykova

2023-10-25 17:32 UTC, galinabykova commented
> Спасибо!!! это помогло. Все рушил toString. На него не было явных тестов (сразу принт), а строчек он занимает много. Добавила на него тесты и процент взлетел @galinabykova

мягкий дедлайн засчитан

2023-10-26 07:06 UTC, galinabykova reviewed
в задании сказано, что "Объектная модель должна содержать,
как минимум, граф, вершину и ребро". Это значит, что у тебя должен быть класс для вершины

2023-10-26 07:59 UTC, galinabykova requested changes

2023-10-26 07:59 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/Graph.java
> +public abstract class Graph<T> {
должен быть метод для изменения объекта, который хранится в вершине

2023-10-26 07:59 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/Graph.java
> +public abstract class Graph<T> {
Кажется, что сейчас использование абстрактного класса (а не интерфейса) не даёт никакого профита. У тебя нет общего состояния у объектов, этот абстрактный класс содержит только описание методов и реализацию одного алгоритма. Это можно сделать с помощью интерфейса (с дефолтным определением метода sortVerticesByDistance).  Мне кажется, лучше использовать интерфейс, потому что один класс может наследовать много интерфейсав и только один класс. Сейчас, если пользователь захочет использовать твой алгоритм для какого-то своего класса, который уже включён в иерархию, он не сможет это сделать. Абстрактный класс же никакого профита в этом случае не даёт.

Также, может быть, стоит вынести сам алгоритм в отдельный класс, который будет принимать на вход объекты, реализующий интерфейс. При такой реализации алгоритм будет максимально независим от графа, и можно будет добавить новый алгоритм, не меняя код интерфейса. Но об этом пункте можно подискутировать

2023-10-26 07:59 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/yakupova/GraphTest.java
> +        var graph = new AdjList<String>();
у тебя здесь фактически три раза написан один код из изменением одной строчки. Можно было бы как-то объединить это, например, вынести общий код в метод, принимающий объект Graph. Но в этом случае копипасты было бы тоже много. JUnit предоставляет механизм для таких ситуаций

```java
    @ParameterizedTest
    @ArgumentsSource(testArgumentsProvider.class)
    void chechSomething(Graph<String> graph) {
    }

    static class testArgumentsProvider implements ArgumentsProvider {
        @Override
        public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    Arguments.of(new AdjList<String>()),
                    Arguments.of(new AdjMatrix<String>())
            );
        }
    }
```

Менять для всех классов слишком больно, попробуй изменить два каких-нибудь теста таким образом (то есть вместо шести тестов сделай два параметризированных).

2023-10-26 09:51 UTC, lnkpv commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/Graph.java
> +public abstract class Graph<T> {
setWeight() для ребер уже есть.
Добавила setId() для вершин (решила хранить у вершин их значение и некоторый id (который правда вообще не нужен в моей реализации, допустим пригодится в решении доп задания с Беллманом-Фордом))

2023-10-26 09:52 UTC, lnkpv commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/Graph.java
> +public abstract class Graph<T> {
Сделала интерфейс. Алгоритм Дейкстры вынесла отдельно (туда же добавится Беллман-Форд в дальнейшем).

2023-10-26 09:52 UTC, lnkpv commented on Task_1_2_2/src/test/java/ru/nsu/yakupova/GraphTest.java
> +        var graph = new AdjList<String>();
Мне так понравился этот метод, что заменила все тесты, кроме toString.

2023-10-26 09:54 UTC, lnkpv commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/Graph.java
> +public abstract class Graph<T> {
Собственно класс вершин у меня уже был (n-ое количество коммитов назад), но в связи с тем, что он не использовался я убрала его. 
Сейчас добавила обратно,  и добавила его использование при создании ребра.

2023-10-26 11:12 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/Graph.java
> +public abstract class Graph<T> {
у тебя сейчас есть небольшое несоответствие в коде, потому что вершинами называются и сами объекты, которые хранятся в вершинах, и вершины. Это немного путает, но, понятно, что это произошло из-за встраивания изначально незапланированного объекта.

Добавление класса вершин сейчас формальное, setId у тебя не будет работать как нужно, потому что фактически у тебя одной вершине графа соответствует много объектов класса Vertex, так как ты создаёшь вершину в ребре, и у каждого ребра своя версия вершины. При изменении Id ты изменишь id только у одного из этих объектов. 

Мне бы хотелось, чтобы ты реализовала версию, в которой в интерфейсе класса Graph появится метод, меняющий объект вершины, однако есть подозрение, что для этого придётся делать много не очень полезных приседаний, поэтому вместо этого можешь при очной защите рассказать почему в текущей реализации это сложно сделать, как можно было бы изначально спроектировать библиотеку, чтобы это работало. В этом случае я ожидаю, что ты нарисуешь некоторые картинки, отображающие связи между классами, в текущей реализации и в реализации с изменение объекта в вершине

2023-10-31 12:30 UTC, lnkpv commented
Я попробовала перестроить все под активное использование Vertex<T>. Примерно это имелось ввиду? @galinabykova

2023-10-31 12:37 UTC, lnkpv commented
В моем случае объект вершины меняет метод добавления вершины. Он добавляет объект в список вершин и возвращает сам объект для использования. (добавляет вершину в случае, если ее еще нет)

2023-10-31 13:03 UTC, galinabykova requested changes

2023-10-31 13:03 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/IncMatrix.java
> +    public Vertex<T> addVertex(T vertexValue) {
кажется, что этот метод не меняет объект вершины. Хочется, чтобы можно было ПОДМЕНИТЬ объект, хранящийся в вершине, сохранив сам объект вершины и, самое главное, все её связи с другими вершинами. Вроде бы в текущей реализации это не сложно реализовать, скорее всего, в отдельном методе. Нужно подменить объект в самой вершине и обновить мапу vertices

2023-10-31 13:04 UTC, lnkpv commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/IncMatrix.java
> +    public Vertex<T> addVertex(T vertexValue) {
Имеется ввиду смена значения вершины? ("A" -> "B")

2023-10-31 13:05 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/IncMatrix.java
> +    public Vertex<T> addVertex(T vertexValue) {
то есть условно у пользователя есть какой-то большой граф, и в нём уже указано куча соседей некоторой вершины. И вот в какой-то момент имя вершины надо переименовать. Хочется, чтобы при этом не надо было заново конструировать граф, а можно было просто поменять имя

2023-10-31 13:06 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/IncMatrix.java
> +    public Vertex<T> addVertex(T vertexValue) {
> Имеется ввиду смена значения вершины? ("A" -> "B")

Да

2023-10-31 13:06 UTC, lnkpv commented on Task_1_2_2/src/main/java/ru/nsu/yakupova/IncMatrix.java
> +    public Vertex<T> addVertex(T vertexValue) {
ааа, хорошо

2023-10-31 14:58 UTC, lnkpv commented
Так, у меня получилось добавить метод changeVertex() для графа, setValue() для вершины. Был нюанс в том, что у меня Hashcode зависел от value - это влекло проблемы после изменения этого значения. Поэтому поменяла немного класс вершин. Теперь когда мы создаем вершину, мы указываем ее значение и некоторый id. В каждой реализации графа я добавила modifications который увеличивается на 1 при каждом добавлении вершины. Он только растет и именно его текущее значение является id для вершины. Теперь hashCode определяется этим id и все работает.

2023-10-31 14:59 UTC, lnkpv commented
Тест на изменение вершины тоже добавила

2023-10-31 15:12 UTC, galinabykova approved these changes

2023-11-01 17:03 UTC, lnkpv commented
Я добавила Беллмана-Форда. Нюанс в том, что отрицательный вес может быть только в ориентированном графе. Я добавила флаг oriented для всех имплементаций. Если oriented=true, то граф ориентирован (это влияет на addEdge, removeEdge). oriented в моей реализации задается при создании графа. Метод сортировки я вынесла в интерфейс через default. Для простоты решила, что в случае орграфа - используем Беллмана-Форда, иначе алгоритм Дейкстры. Добавила новый тест (и класс с новыми параметрами для тестов - ориентированными графами) @galinabykova

2023-11-02 08:31 UTC, galinabykova approved these changes

2023-11-02 08:35 UTC, merged