Task_1_3_1
lnkpv/OOP pull request #5
Opened 2023-11-07 11:52 UTC by lnkpv

2023-11-07 12:02 UTC, lnkpv commented
Я помню, что должен быть тест с огромным файлом. Но есть вопросы:
1) Как лучше всего его сгенерировать?
2) Как решить проблему с его загрузкой на гитхаб? (я помню обсуждения на тему того, что его нельзя подгружать, не поместится)
@galinabykova

2023-11-07 12:14 UTC, galinabykova commented
> Я помню, что должен быть тест с огромным файлом. Но есть вопросы:
> 
> 1. Как лучше всего его сгенерировать?
> 2. Как решить проблему с его загрузкой на гитхаб? (я помню обсуждения на тему того, что его нельзя подгружать, не поместится)
>    @galinabykova

Большой файлик надо генерировать в начале теста (каким-нибудь Writer или ещё как-нибудь) и удалять в конце. Скорее всего при этом у тебя возникнут проблемы с чтением из ресуров, потому что такой файлик не надо будет писать в ресурсы, его нужно читать просто как файлик где-то в файловой системе, не из ресурсов. Чтобы решить эту проблему, можешь добавить флаг, который будет указывать, откуда читаем, или придумать иное решение

2023-11-07 12:14 UTC, galinabykova requested changes

2023-11-07 12:14 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/yakupova/SubstringSearchTest.java
> +        List<Integer> positions = SubstringSearch.find("build/resources/main/basic.txt", "бра");
так не надо загружать файлик ресурсов. Здесь ты привязывашься к тому месту, где будут запускаться тесты, лучше загружать ресурсы через getResource, тогда файлики будут искаться относительно места, где находится запускаемый класс

2023-11-07 12:34 UTC, lnkpv commented on Task_1_3_1/src/test/java/ru/nsu/yakupova/SubstringSearchTest.java
> +        List<Integer> positions = SubstringSearch.find("build/resources/main/basic.txt", "бра");
Добавила метод с getResource. Теперь достаточно только имени файла

2023-11-07 12:45 UTC, galinabykova requested changes
с ресурсами верно, нужно ещё большой файлик)

2023-11-07 14:32 UTC, lnkpv commented
> с ресурсами верно, нужно ещё большой файлик)

Для большого файлика сделала метод с его генерацией.
Файлик random.txt по умолчанию пустой. Но в одном из тестов он генерируется (метод generateFile()), заполняется кучей строк), используется для поиска подстроки и в конце очищается (возвращается в исходное его состояние).
@galinabykova

2023-11-08 04:07 UTC, galinabykova requested changes

2023-11-08 04:07 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/yakupova/SubstringSearch.java
> +    public static void generateFile(String filename) {
мне кажется, идея писать в ресурсы не очень удачная. Например, а что если твою программу будут запускать через jarник (который readonly)? 
Ресурсы скорее нужны, чтобы добавить какие-то постоянные данные в сборку, картиночки, иконочки, всё такое. Если не хочешь делать флаг, попробуй разделить свою реализацию так, чтобы у тебя была функция, которая принимала InputStream. Всякие кириллицы\иероглифы тестируй на ней. И сделай коротенькую функцию с чтением файла не из ресурса, её уже протестируй с большим файлом. Можно подумать, что ещё можно сделать, но писать в ресуры точно не стоит

2023-11-11 13:59 UTC, lnkpv commented
Теперь у меня есть флажок resource (по умолчанию true).
Если срабатывает метод generateFile(), то resource становится false, пока не выполнятся все методы внутри функции find().

find() теперь выглядит как оболочка всего происходящего.
fileReader() устанавливает reader (определяется его по-разному, в зависимости от resource)
findSubstring() теперь содержит чисто алгоритм поиска подстроки.

Также добавила тесты на английском и японском
@galinabykova

2023-11-12 06:10 UTC, galinabykova approved these changes
оставила пару комментариев, но это скорее заметки мне для очной защиты, исправлять не надо

2023-11-12 06:10 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/yakupova/SubstringSearch.java
> +    public void clearHugeFile(String filename) {
тут, наверно, можно было просто сделать удаление файла

2023-11-12 06:10 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/yakupova/SubstringSearch.java
> +    public void generateFile(String filename) {
кажется, что этот файл и clearHugeFile не имеют явного отношения к этому классу, а просто используются в тестах. Наверное, их стоило бы вынести в отдельный файл, может быть, вообще в тесты

2023-11-12 06:10 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/yakupova/SubstringSearch.java
> +    public void generateFile(String filename) {
хотя у тебя тут интересная логика использования, давай просто обсудим при очной защите, как сделала ты и почему так

2023-11-12 09:30 UTC, lnkpv commented on Task_1_3_1/src/main/java/ru/nsu/yakupova/SubstringSearch.java
> +    public void generateFile(String filename) {
Хорошо) 
Я несколько раз сменила модель мышления, думаю тут и правда есть что обсудить :D

2023-11-22 04:02 UTC, merged