Task_1_4_1
lnkpv/OOP pull request #6
Opened 2023-11-22 15:00 UTC by lnkpv

2023-11-22 16:40 UTC, galinabykova requested changes

2023-11-22 16:40 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/yakupova/StudentsBook.java
> +        for (String key : keys) {
перепиши это, пожалуйста, с использованием StreamAPI

2023-11-22 16:40 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/yakupova/StudentsBook.java
> +    public boolean canGetRedDiploma() {
это тоже перепиши с использованием StreamAPI

2023-11-22 16:40 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/yakupova/StudentsBook.java
> +    public boolean canGetRedDiploma() {
в этом методе не должно остаться циклов и лучше не использовать forEach

2023-11-22 16:40 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/yakupova/Subject.java
> +    public String name;
лучше всё же обернуть в геттеры/сеттеры и сделать поля приватными. Вдруг потом поменяется что-то в реализации класса

2023-11-22 16:40 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/yakupova/StudentsBookTest.java
нужны тесты на нарушение разных условий, получения крастного диплома, например, тест, в котором среди последних оценок будут тройки

2023-11-22 21:14 UTC, lnkpv commented
1) Добавила три крупных теста с проверкой ключевых правил на получение красного диплома.
2) Избавилась от циклов, только stream

Примечание: циклы остались только в трех методах принта.
@galinabykova

2023-11-22 21:16 UTC, lnkpv commented
геттеры и сеттеры тоже добавила

2023-11-23 10:59 UTC, galinabykova approved these changes

2023-11-23 11:00 UTC, merged