Task_1_5_1
lnkpv/OOP pull request #7
Opened 2023-12-01 00:00 UTC by lnkpv

2023-12-01 00:54 UTC, lnkpv commented
Сделала реализацию сразу с комплексными числами.
Калькулятор принимает и вещественные и комплексные.
В случае вещественных происходит приведение их к комплексным (+ 0*i).
Добавила исключения на деление, логарифм, корень (для вещественных чисел, т.е. +0*i).
Тесты на эти исключения есть.
Для комплексных добавила парсинг с помощью паттернов.
Многие операции имеют комментарии с описанием формул.
@galinabykova

2023-12-01 10:18 UTC, galinabykova requested changes

2023-12-01 10:18 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/Calculator.java
> +                        stack.push(a.add(b));
Сейчас у тебя все вычислительные операции находятся в одном классе. Это логично для такой маленькой задачки, однако давай представим, что твой калькулятор в будущем будет расширяться. Со временем класс ComplexNumber разрастётся до невероятных размеров. Мы хотим сделать что-то более расширяемое.

Кажется, что в калькуляторе, операции - это важные сущности, предполагается, что в этом задании у тебя будут отдельные классы для операций, имеющие общего предка. Создание объектов таких классов лучше вынести в отдельный класс (посмотри паттерн фабрика). Предполагается, что при добавлении операции, тебе не нужно будет менять код в парсере и интерпретаторе, нужно будет лишь чуть-чуть модифицировать фабрику, добавить новый класс и может быть указать Операции, что у неё теперь новый наследник (если используешь sealed)

2023-12-01 10:18 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/MyException.java
> +class MyException extends IllegalArgumentException {
Нужно продумать, какие бывают исключения и должна быть иерархия исключений (хотя бы два уровня)

2023-12-01 10:18 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/MyException.java
> +class MyException extends IllegalArgumentException {
сообщение в исключении - это просто подсказка для программиста, лучше создавать для каждого исключения отдельный класс, чтобы можно было удобно его отловить.

2023-12-01 10:30 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/Calculator.java
> +                        stack.push(a.add(b));
"Кажется, что в калькуляторе, операции - это важные сущности, предполагается, что в этом задании у тебя будут отдельные классы для операций, имеющие общего предка. Создание объектов таких классов лучше вынести в отдельный класс (посмотри паттерн фабрика)" - вот это совет

"Предполагается, что при добавлении операции, тебе не нужно будет менять код в парсере и интерпретаторе," - вот это обязательно надо сделать

2023-12-05 21:10 UTC, lnkpv commented
Итак, изменения:
Operation - интерфейс для операций.
OperationType - enum для операций.
Все операции - классы, которые имплементируют интерфейс.
SimpleCalculator - класс, в котором к аргументам выбирается и применяется операция.
Calculator - главный класс с калькулятором (считывание входной строки, парсинг, стек с аргументами, операциями, результатом)
ComplexNumber - тот же класс для комплексных, что и был, но уже без реализации операций.
Добавила исключения, пыталась выстроить иерархию для негативных аргументов (но не знаю, насколько поняла, что сделала).
@galinabykova

2023-12-06 10:23 UTC, galinabykova requested changes

2023-12-06 10:23 UTC, galinabykova commented on Task_1_5_1/src/test/java/ru/nsu/yakupova/CalculatorTest.java
Хочется тест на отдельный тест на каждую операцию, чтобы в процессе поддержания кода, была легко отловить ошибку

2023-12-06 10:23 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/Plus.java
> +        return this.result;
тут исправлять не надо, просто интересно, почему ты решила сохранять результат в переменную, а не вычислять его в этом методе?

2023-12-06 10:30 UTC, lnkpv commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/Plus.java
> +        return this.result;
Тут в этом нет хитроумного замысла. 
Я просто делала лабу очень поздно и вот такая идея пришла в мою сонную голову :D 
Просто в случае если бы результат вычислений использовался неоднократно, то считать его каждый раз было бы не очень хорошо, но здесь все результаты одноразовые, так что да, я могла спокойно посчитать его в getResult

2023-12-06 10:31 UTC, lnkpv commented on Task_1_5_1/src/test/java/ru/nsu/yakupova/CalculatorTest.java
Имеются в виду отдельные тесты на PLUS, MINUS, MULTIPLY и т.д.?

2023-12-06 10:43 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/Plus.java
> +        return this.result;
Поняла)

2023-12-06 10:44 UTC, galinabykova commented on Task_1_5_1/src/test/java/ru/nsu/yakupova/CalculatorTest.java
Ага

2023-12-06 11:27 UTC, galinabykova approved these changes

2023-12-06 11:27 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/yakupova/SimpleCalculator.java
> +public class SimpleCalculator {
мне кажется, это не очень удачное название для этого класса, но эта мелочь, можешь тут не  исправлять)

2023-12-06 11:28 UTC, merged